import Head from "next/head";
import { useEffect, useState } from "react";
import TodoHandler from "../components/todohandler";
import { localStorageUtils } from "../lib/storage";

export default function Home() {
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    localStorageUtils.cleanupTodos();
    setLoaded(true);
  }, []);

  return (
    <div>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </Head>

      <main>{loaded && <TodoHandler />}</main>

      <footer></footer>
    </div>
  );
}
